# Import Required libraries
import logging
from langchain_core.output_parsers import PydanticOutputParser

# Import project files
from schemas.cover_letter_schema import CoverLetterSchema
from schemas.gap_schema import GapLLMSchema
from prompts.cover_letter_prompt import SYSTEM_PROMPT, USER_PROMPT
from services.llm_service import get_llm_model
from utils.llm_retry import safe_llm_call

logger = logging.getLogger(__name__)

class CoverLetterAgent:
    """
    Generates a personalized cover letter using the candidate's
    resume, job description, and gap analysis.
    """

    def __init__(self):
        """
        Initialize the Cover Letter Agent.

        Args:
            llm: LangChain chat model supporting structured output.
        """
        self.llm = get_llm_model()
        self.agent_name = "Cover Letter Agent"
        # Pydantic parser ensures structured output (GapSchema validation)
        self.parser = PydanticOutputParser(
            pydantic_object=CoverLetterSchema
        )

    def generate_cover_letter(
        self,
        resume_context: str,
        job_description: str,
        gap_analysis: str,
        company_name: str,
        title: str,
        tone: str = "Professional",
    ) -> CoverLetterSchema:
        """
        Generate a personalized cover letter.

        Args:
            resume_context: Parsed resume information.
            job_description: Target job description.
            gap_analysis: Gap analysis generated by JobLens.
            company_name: Company name.
            title: Target job title.
            tone: Desired writing tone.

        Returns:
            CoverLetterSchema
        """

        logger.info("Generating personalized cover letter...")

        format_instructions = self.parser.get_format_instructions()

        try:
            prompt = [
                ("system", SYSTEM_PROMPT),
                (
                    "human",
                    USER_PROMPT.format(
                        resume_context=resume_context,
                        job_description=job_description,
                        gap_analysis=gap_analysis,
                        company_name=company_name,
                        job_title=title,
                        tone=tone,
                        format_instructions = format_instructions
                    ),
                ),
            ]

            logger.info(f"Cover letter prompt length: {len(prompt)}")

            # Call LLM 
            response = safe_llm_call(
                lambda: self.llm.invoke(prompt),
                prompt=prompt,
                agent_name=self.agent_name,
            )

            logger.info("Cover letter generated successfully.")

            result = self.parser.parse(response.content)

            return result

        except Exception as e:
            logger.exception("Failed to generate cover letter.")
            raise RuntimeError(
                f"Cover letter generation failed: {str(e)}"
            ) from e