#import required libraries
from langchain_core.output_parsers import PydanticOutputParser

# import project files
from schemas.market_schema import MarketSchema, LiveJob
from schemas.resume_schema import ResumeSchema
from schemas.job_schema import JobSchema
from schemas.gap_schema import GapSchema
from services.llm_service import get_llm_model
from tools.adzuno_job_search_tool import search_jobs
from tools.tool_executor import ToolExecutor
from utils.llm_retry import safe_llm_call
from prompts.market_prompt import MARKET_PROMPT
import json
from services.context_builder import build_market_context
from utils.logger import get_logger

# Initialize logger
logger = get_logger(__name__)

class MarketAgent:

    def __init__(self):

        # bind tools 
        self.tool_llm = get_llm_model().bind_tools([search_jobs])
        self.analysis_llm = get_llm_model()
        self.executor = ToolExecutor(tools = [search_jobs])
        self.agent_name = "Market Agent"
        self.parser = PydanticOutputParser(pydantic_object=MarketSchema)

    def analyze_market(
        self,
        resume_analysis,
        job_analysis,
        gap_analysis,
        country: str = "au"
    ):
        """
        Analyze the current job market for the candidate.

        Workflow
        --------
        1. Search live jobs using the job search tool.
        2. Convert retrieved jobs into lightweight LiveJob objects.
        3. Build a compact candidate context.
        4. Ask the LLM to analyze the market using the candidate profile
        and the retrieved jobs.
        5. Combine:
            - Live jobs (tool output)
            - Market analysis (LLM output)
        into the final MarketSchema.
        """

        # Step 1: Search live jobs using the tool
        tool_prompt = f"""
        Search for live job openings.

        Target Role:
        {job_analysis["title"]}

        Country:
        {country}

        Retrieve up to 5 matching jobs.
        """

        ai_message = self.tool_llm.invoke(tool_prompt)

        # Initialize variables
        jobs = []
        live_jobs = []

        # Execute tool if the LLM requested one
        if ai_message.tool_calls:

            tool_call = ai_message.tool_calls[0]

            jobs = self.executor.execute(
                tool_name=tool_call["name"],
                tool_args=tool_call["args"]
            )

            # Convert tool output into LiveJob objects
            live_jobs = [
                LiveJob(
                    title=job["title"],
                    company=job["company"],
                    location=job["location"],
                    description=job["job_description"],
                    apply_url=job["apply_url"],
                )
                for job in jobs
            ]

        else:
            logger.warning("No tool call generated by Market Agent.")

        logger.info(f"Retrieved {len(jobs)} live jobs.")

        
        # Step 2: Convert graph state back into schema objects
        resume = ResumeSchema(**resume_analysis)
        target_job = JobSchema(**job_analysis)
        gap = GapSchema(**gap_analysis)

        
        # Step 3: Build candidate market context
        market_context = build_market_context(
            resume,
            target_job,
            gap
        )

        
        # Step 4: Reduce job information before sending to the LLM
        compact_jobs = [
            {
                "title": job["title"],
                "company": job["company"],
                "location": job["location"],
                "description": job["job_description"][:120]
            }
            for job in jobs
        ]

        # Step 5: Build prompt
        prompt = MARKET_PROMPT.format(
            market_context=market_context,
            jobs=json.dumps(compact_jobs, indent=2)
        )

        
        # Step 6: Generate market analysis
        response = safe_llm_call(
            lambda: self.analysis_llm.invoke(prompt),
            prompt=prompt,
            agent_name=self.agent_name,
        )

        logger.info("Market Agent Response:")
        logger.info(response.content)

        
        # Step 7: Parse LLM response
        analysis = json.loads(response.content)

        print(f"Final Analysis {analysis}")

        
        # Step 8: Build the final MarketSchema
        return MarketSchema(
            live_jobs=live_jobs,
            similar_roles=analysis.get("similar_roles", []),
            alternative_roles=analysis.get("alternative_roles", []),
            trending_skills=analysis.get("trending_skills", []),
            market_summary=analysis.get("market_summary", "")
        )




        